name: publish php docker image
on: [push]
jobs:
  liaisons-dangereuses-docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Test
        run: |
          docker build . --tag ghcr.io/timoogo/liaisons-dangereuses-docker-publish:latest
          docker run ghcr.io/timoogo/liaisons-dangereuses-docker-publish:latest
          docker push ghcr.io/timoogo/liaisons-dangereuses-docker-publish:latest